---
# Base configuration for the experiments for the poisson arrivals
network-path: networks
resources-path: ../resources
output-path: ../analysis/experiments/poisson_arrivals/rv-nf-masa-age-gender-face-n_workers-rerun-short
general-outputfile: generalOutput_poisson_arrivals.csv
mean-service-time:
  128M: 1096.65320827
  256M: 643.9415593100001
  4G: 368.53780722

  2G: 1291
  1G: 1322
  512M: 1367
rho: [1]
memory-constraints: [512M, 1G, 2G]
#modes: [masa-e, bulk, deepeye]
modes: [masa-e]
networks: [[AgeNet, GenderNet, FaceNet]]
ait_multipliers: [0.6, 0.7, 0.8, 0.9, 0.925, 0.95, 0.975, 1]
n_workers: [2, 3, 4, 5, 6]
repetitions: 10
cmd-base: bin/Exp_poisson_arrival_rv_nf
build-folder: cmake-build-release