---
# Base configuration for the experiments for the poisson arrivals
network-path: networks
resources-path: ../resources
output-path: ../analysis/experiments/poisson_arrivals/rv-nf-masa-memory-matters-agenet
general-outputfile: generalOutput_poisson_arrivals.csv
mean-service-time:
  128M: 1096.65320827
  256M: 643.9415593100001
  4G: 368.53780722

  2G: 1291
  1G: 1322
  512M: 1367
  64M: 1367
  32M: 1367
#  512M: 1367
rho: [1]
memory-constraints: [32M, 64M, 128M, 256M, 512M, 1G, 2G]
#modes: [masa-e, bulk, deepeye]
modes: [bulk, deepeye]
networks: [[AgeNet]]
ait_multipliers: [1]
n_workers: [2]
repetitions: 3
cmd-base: bin/Exp_poisson_arrival_rv_nf
build-folder: cmake-build-debug
poisson-distribution: false