---
# Base configuration for the experiments for the poisson arrivals
network-path: networks
resources-path: ../resources
output-path: ../analysis/experiments/poisson_arrivals/rv-nf-multi-facenet
general-outputfile: generalOutput_poisson_arrivals.csv
mean-service-time:
  128M: 1096.65320827
#  1G: 393.55182419
  256M: 643.9415593100001
#  2G: 472.64636834
  4G: 368.53780722
#  512M: 417.98935261
  # 1G: 812.97
  # 1G: 1550.2
  1G: 3916.7
  # 2G: 925.08
  # 2G: 1543.2
  2G: 3926.5
  # 512M: 903.7
  # 512M: 1578.4
  512M: 3922.8
rho: [1]
# rho: [0.8]
memory-constraints: [2G, 1G, 512M]
# memory-constraints: [512M]
modes: [partial, bulk, deepeye, linear]
# modes: [deepeye]
repetitions: 50
cmd-base: Exp_poisson_arrival_rv_nf
build-folder: cmake-build-debug