---
# Base configuration for the experiments for the poisson arrivals
network-path: networks
resources-path: ../resources
output-path: ../analysis/experiments/poisson_arrivals/rv-nf-check-run-100-4-networks
general-outputfile: generalOutput_poisson_arrivals.csv
mean-service-time:
  128M: 1096.65320827
#  1G: 393.55182419
  256M: 643.9415593100001
#  2G: 472.64636834
  4G: 368.53780722
#  512M: 417.98935261
  # 1G: 812.97
  1G: 1866.880805
  # 2G: 925.08
  2G: 1870.607122
  # 512M: 903.7
  512M: 1871.771445
rho: [0.7, 0.8, 0.9, 0.95]
# rho: [0.8]
memory-constraints: [2G, 1G, 512M]
# memory-constraints: [512M]
modes: [partial, bulk, deepeye, linear]
# modes: [deepeye]
repetitions: 100
cmd-base: Exp_poisson_arrival_rv_nf
build-folder: cmake-build-debug