---
# Base configuration for the experiments for the poisson arrivals
network-path: networks
resources-path: ../resources
output-path: ../analysis/experiments/poisson_arrivals/rv-nf-check-run
general-outputfile: generalOutput_poisson_arrivals.csv
mean-service-time:
  128M: 1096.65320827
  1G: 393.55182419
  256M: 643.9415593100001
  2G: 472.64636834
  4G: 368.53780722
  512M: 417.98935261