---
# Base configuration for the experiments for the poisson arrivals
network-path: networks
resources-path: ./resources
output-path: ./analysis/experiments/poisson_arrivals/rv-nf-multi-facenet-rpi-4g-exp
general-outputfile: generalOutput_poisson_arrivals.csv
mean-service-time:
  128M: 1096.65320827
  256M: 643.9415593100001
  512M: 79702
  1G: 31384
  2G: 8004
  4G: 7803
rho: [1]
memory-constraints: [4G]
modes: [execprio-inter, execprio, partial, bulk, deepeye, linear]
repetitions: 10
cmd-base: ./bin/Exp_poisson_arrival_rv_nf
build-folder: .